name: Tailscale
description: Connect to your [Tailscale](https://tailscale.com/) network.
author: https://github.com/steved
requirements:
  - bash
  - tailscale
  - tailscaled
configuration:
  properties:
    client-id:
      type: string
      description: "Client ID. When no client-secret-env is supplied, defaults to using workload identity federation."
    client-secret-env:
      type: string
      description: "The environment variable that the OAuth client secret is stored in."
    audience:
      type: string
      description: "OIDC token audience. Defaults to: tailscale.com."
    tags:
      type: string
      description: "The device tags this pipeline will use."
    hostname:
      type: string
      description: "The hostname to use."
    timeout:
      type: number
      description: "Connection timeout value in seconds."
  required:
    - tags
  additionalProperties: false
