#!/bin/bash

set -euo pipefail

tags="${BUILDKITE_PLUGIN_TAILSCALE_TAGS?"Tags must be set"}"

client_id="${BUILDKITE_PLUGIN_TAILSCALE_CLIENT_ID:-}"
client_secret_env="${BUILDKITE_PLUGIN_TAILSCALE_CLIENT_SECRET_ENV:-}"
audience="${BUILDKITE_PLUGIN_TAILSCALE_AUDIENCE:-tailscale.com}"

if [[ -z "$client_id" ]] && [[ -z "$client_secret_env" ]]; then
  echo "Client ID or client secret must be set"
  exit 1
fi

hostname="${BUILDKITE_PLUGIN_TAILSCALE_HOSTNAME:-buildkite-${BUILDKITE_AGENT_NAME:-$(hostname)}}"
timeout="${BUILDKITE_PLUGIN_TAILSCALE_TIMEOUT:-120}"

nohup tailscaled --state=mem: < /dev/null > /var/log/tailscaled.log 2> /var/log/tailscaled.err.log &

echo "~~~ Waiting for Tailscale daemon to start..."
timeout "$timeout" /bin/bash -c "until tailscale status --json >/dev/null 2>&1; do sleep 1; done"
echo "✅ Tailscale daemon started successfully"

echo "🌐 Connecting to Tailscale network..."
if [[ -n "$client_id" ]]; then
  id_token=$(buildkite-agent oidc request-token --audience "$audience")
  tailscale up \
    --client-id="${client_id}?preauthorized=true&ephemeral=true" \
    --id-token="$id_token" \
    --hostname="$hostname" \
    --advertise-tags="$tags" \
    --accept-routes \
    --timeout "${timeout}s"
else
  authkey="${!client_secret_env}?preauthorized=true&ephemeral=true"
  tailscale up \
    --authkey="$authkey" \
    --hostname="$hostname" \
    --advertise-tags="$tags" \
    --accept-routes \
    --timeout "${timeout}s"
fi

echo "✅ Successfully connected to Tailscale!"

echo "📊 Connection status:"
tailscale status
